apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: nodejs-ex-01
  labels:
    app: nodejs-ex-01
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: "https://github.com/sclorg/nodejs-ex"
    contextDir: /
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: "nodejs:22-minimal-ubi10"
  output:
    to:
      kind: ImageStreamTag
      name: "nodejs-ex-01:latest"
  triggers:
    - type: GitHub
      github:
        secretReference:
          name: nodejs-ex-01-github-webhook-secret
    - type: Generic
      generic:
        secretReference:
          name: nodejs-ex-01-generic-webhook-secret
    - type: ImageChange

