apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-ex-01
  labels:
    app: nodejs-ex-01
    app.kubernetes.io/name: nodejs-ex-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-ex-01
  template:
    metadata:
      labels:
        app: nodejs-ex-01
    spec:
      containers:
        - name: nodejs-ex-01
          image: image-registry.openshift-image-registry.svc:5000/aman-redhat01-dev/nodejs-ex-01:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
