apiVersion: v1
kind: Service
metadata:
  name: nodejs-ex-01
  labels:
    app: nodejs-ex-01
spec:
  selector:
    app: nodejs-ex-01
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
